board_size: 5
location_replay_buffer: ''
thread_count: 1
games_per_thread: 24
games_per_eval_thread: 24
mcts_simulations: 101
amount_evaluator_iterations: 25
state_history_length: 3
pipeline_runs: 3
improvement_percentage_threshold: 0.51
custom_batch_size: 1024
epochs: 700
input_states: 4
c_puct: 4.0
temperature: 0.97

#path_to_model_to_load: '/home/marcel/PycharmProjects/pikoAlphaGo/components/nn/models/model20210310-102859'
path_to_model_to_load: None
use_old_replay_buffer: False